# coding: utf-8

"""
    X-Road Security Server Admin API

    X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.  # noqa: E501

    OpenAPI spec version: 1.0.30
    Contact: info@niis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OcspResponderDiagnostics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'distinguished_name': 'str',
        'ocsp_responders': 'list[OcspResponder]'
    }

    attribute_map = {
        'distinguished_name': 'distinguished_name',
        'ocsp_responders': 'ocsp_responders'
    }

    def __init__(self, distinguished_name=None, ocsp_responders=None):  # noqa: E501
        """OcspResponderDiagnostics - a model defined in Swagger"""  # noqa: E501
        self._distinguished_name = None
        self._ocsp_responders = None
        self.discriminator = None
        self.distinguished_name = distinguished_name
        self.ocsp_responders = ocsp_responders

    @property
    def distinguished_name(self):
        """Gets the distinguished_name of this OcspResponderDiagnostics.  # noqa: E501

        CA distinguished name  # noqa: E501

        :return: The distinguished_name of this OcspResponderDiagnostics.  # noqa: E501
        :rtype: str
        """
        return self._distinguished_name

    @distinguished_name.setter
    def distinguished_name(self, distinguished_name):
        """Sets the distinguished_name of this OcspResponderDiagnostics.

        CA distinguished name  # noqa: E501

        :param distinguished_name: The distinguished_name of this OcspResponderDiagnostics.  # noqa: E501
        :type: str
        """
        if distinguished_name is None:
            raise ValueError("Invalid value for `distinguished_name`, must not be `None`")  # noqa: E501

        self._distinguished_name = distinguished_name

    @property
    def ocsp_responders(self):
        """Gets the ocsp_responders of this OcspResponderDiagnostics.  # noqa: E501


        :return: The ocsp_responders of this OcspResponderDiagnostics.  # noqa: E501
        :rtype: list[OcspResponder]
        """
        return self._ocsp_responders

    @ocsp_responders.setter
    def ocsp_responders(self, ocsp_responders):
        """Sets the ocsp_responders of this OcspResponderDiagnostics.


        :param ocsp_responders: The ocsp_responders of this OcspResponderDiagnostics.  # noqa: E501
        :type: list[OcspResponder]
        """
        if ocsp_responders is None:
            raise ValueError("Invalid value for `ocsp_responders`, must not be `None`")  # noqa: E501

        self._ocsp_responders = ocsp_responders

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OcspResponderDiagnostics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OcspResponderDiagnostics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
