# coding: utf-8

"""
    X-Road Security Server Admin API

    X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.  # noqa: E501

    OpenAPI spec version: 1.0.30
    Contact: info@niis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ServiceUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'timeout': 'int',
        'ssl_auth': 'bool',
        'url_all': 'bool',
        'timeout_all': 'bool',
        'ssl_auth_all': 'bool',
        'ignore_warnings': 'bool'
    }

    attribute_map = {
        'url': 'url',
        'timeout': 'timeout',
        'ssl_auth': 'ssl_auth',
        'url_all': 'url_all',
        'timeout_all': 'timeout_all',
        'ssl_auth_all': 'ssl_auth_all',
        'ignore_warnings': 'ignore_warnings'
    }

    def __init__(self, url=None, timeout=None, ssl_auth=None, url_all=False, timeout_all=False, ssl_auth_all=False, ignore_warnings=False):  # noqa: E501
        """ServiceUpdate - a model defined in Swagger"""  # noqa: E501
        self._url = None
        self._timeout = None
        self._ssl_auth = None
        self._url_all = None
        self._timeout_all = None
        self._ssl_auth_all = None
        self._ignore_warnings = None
        self.discriminator = None
        self.url = url
        self.timeout = timeout
        self.ssl_auth = ssl_auth
        if url_all is not None:
            self.url_all = url_all
        if timeout_all is not None:
            self.timeout_all = timeout_all
        if ssl_auth_all is not None:
            self.ssl_auth_all = ssl_auth_all
        if ignore_warnings is not None:
            self.ignore_warnings = ignore_warnings

    @property
    def url(self):
        """Gets the url of this ServiceUpdate.  # noqa: E501

        service url  # noqa: E501

        :return: The url of this ServiceUpdate.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ServiceUpdate.

        service url  # noqa: E501

        :param url: The url of this ServiceUpdate.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def timeout(self):
        """Gets the timeout of this ServiceUpdate.  # noqa: E501

        service time out value  # noqa: E501

        :return: The timeout of this ServiceUpdate.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this ServiceUpdate.

        service time out value  # noqa: E501

        :param timeout: The timeout of this ServiceUpdate.  # noqa: E501
        :type: int
        """
        if timeout is None:
            raise ValueError("Invalid value for `timeout`, must not be `None`")  # noqa: E501

        self._timeout = timeout

    @property
    def ssl_auth(self):
        """Gets the ssl_auth of this ServiceUpdate.  # noqa: E501

        service ssl auth  # noqa: E501

        :return: The ssl_auth of this ServiceUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._ssl_auth

    @ssl_auth.setter
    def ssl_auth(self, ssl_auth):
        """Sets the ssl_auth of this ServiceUpdate.

        service ssl auth  # noqa: E501

        :param ssl_auth: The ssl_auth of this ServiceUpdate.  # noqa: E501
        :type: bool
        """
        if ssl_auth is None:
            raise ValueError("Invalid value for `ssl_auth`, must not be `None`")  # noqa: E501

        self._ssl_auth = ssl_auth

    @property
    def url_all(self):
        """Gets the url_all of this ServiceUpdate.  # noqa: E501

        url is applied for all services  # noqa: E501

        :return: The url_all of this ServiceUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._url_all

    @url_all.setter
    def url_all(self, url_all):
        """Sets the url_all of this ServiceUpdate.

        url is applied for all services  # noqa: E501

        :param url_all: The url_all of this ServiceUpdate.  # noqa: E501
        :type: bool
        """

        self._url_all = url_all

    @property
    def timeout_all(self):
        """Gets the timeout_all of this ServiceUpdate.  # noqa: E501

        timeout value is applied for all services  # noqa: E501

        :return: The timeout_all of this ServiceUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._timeout_all

    @timeout_all.setter
    def timeout_all(self, timeout_all):
        """Sets the timeout_all of this ServiceUpdate.

        timeout value is applied for all services  # noqa: E501

        :param timeout_all: The timeout_all of this ServiceUpdate.  # noqa: E501
        :type: bool
        """

        self._timeout_all = timeout_all

    @property
    def ssl_auth_all(self):
        """Gets the ssl_auth_all of this ServiceUpdate.  # noqa: E501

        ssl authentication is applied for all services  # noqa: E501

        :return: The ssl_auth_all of this ServiceUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._ssl_auth_all

    @ssl_auth_all.setter
    def ssl_auth_all(self, ssl_auth_all):
        """Sets the ssl_auth_all of this ServiceUpdate.

        ssl authentication is applied for all services  # noqa: E501

        :param ssl_auth_all: The ssl_auth_all of this ServiceUpdate.  # noqa: E501
        :type: bool
        """

        self._ssl_auth_all = ssl_auth_all

    @property
    def ignore_warnings(self):
        """Gets the ignore_warnings of this ServiceUpdate.  # noqa: E501

        if true, any ignorable warnings are ignored. if false (or missing), any warnings cause request to fail  # noqa: E501

        :return: The ignore_warnings of this ServiceUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._ignore_warnings

    @ignore_warnings.setter
    def ignore_warnings(self, ignore_warnings):
        """Sets the ignore_warnings of this ServiceUpdate.

        if true, any ignorable warnings are ignored. if false (or missing), any warnings cause request to fail  # noqa: E501

        :param ignore_warnings: The ignore_warnings of this ServiceUpdate.  # noqa: E501
        :type: bool
        """

        self._ignore_warnings = ignore_warnings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServiceUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
