# coding: utf-8

"""
    X-Road Security Server Admin API

    X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.  # noqa: E501

    OpenAPI spec version: 1.0.31
    Contact: info@niis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ErrorInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'error': 'CodeWithDetails',
        'warnings': 'list[CodeWithDetails]'
    }

    attribute_map = {
        'status': 'status',
        'error': 'error',
        'warnings': 'warnings'
    }

    def __init__(self, status=None, error=None, warnings=None):  # noqa: E501
        """ErrorInfo - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._error = None
        self._warnings = None
        self.discriminator = None
        self.status = status
        if error is not None:
            self.error = error
        if warnings is not None:
            self.warnings = warnings

    @property
    def status(self):
        """Gets the status of this ErrorInfo.  # noqa: E501

        http status code  # noqa: E501

        :return: The status of this ErrorInfo.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ErrorInfo.

        http status code  # noqa: E501

        :param status: The status of this ErrorInfo.  # noqa: E501
        :type: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def error(self):
        """Gets the error of this ErrorInfo.  # noqa: E501


        :return: The error of this ErrorInfo.  # noqa: E501
        :rtype: CodeWithDetails
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this ErrorInfo.


        :param error: The error of this ErrorInfo.  # noqa: E501
        :type: CodeWithDetails
        """

        self._error = error

    @property
    def warnings(self):
        """Gets the warnings of this ErrorInfo.  # noqa: E501

        warnings that could be ignored  # noqa: E501

        :return: The warnings of this ErrorInfo.  # noqa: E501
        :rtype: list[CodeWithDetails]
        """
        return self._warnings

    @warnings.setter
    def warnings(self, warnings):
        """Sets the warnings of this ErrorInfo.

        warnings that could be ignored  # noqa: E501

        :param warnings: The warnings of this ErrorInfo.  # noqa: E501
        :type: list[CodeWithDetails]
        """

        self._warnings = warnings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ErrorInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ErrorInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
