# coding: utf-8

"""
    X-Road Security Server Admin API

    X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.  # noqa: E501

    OpenAPI spec version: 1.0.31
    Contact: info@niis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IgnoreWarnings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ignore_warnings': 'bool'
    }

    attribute_map = {
        'ignore_warnings': 'ignore_warnings'
    }

    def __init__(self, ignore_warnings=False):  # noqa: E501
        """IgnoreWarnings - a model defined in Swagger"""  # noqa: E501
        self._ignore_warnings = None
        self.discriminator = None
        if ignore_warnings is not None:
            self.ignore_warnings = ignore_warnings

    @property
    def ignore_warnings(self):
        """Gets the ignore_warnings of this IgnoreWarnings.  # noqa: E501

        if true, any ignorable warnings are ignored. if false (or missing), any warnings cause request to fail  # noqa: E501

        :return: The ignore_warnings of this IgnoreWarnings.  # noqa: E501
        :rtype: bool
        """
        return self._ignore_warnings

    @ignore_warnings.setter
    def ignore_warnings(self, ignore_warnings):
        """Sets the ignore_warnings of this IgnoreWarnings.

        if true, any ignorable warnings are ignored. if false (or missing), any warnings cause request to fail  # noqa: E501

        :param ignore_warnings: The ignore_warnings of this IgnoreWarnings.  # noqa: E501
        :type: bool
        """

        self._ignore_warnings = ignore_warnings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IgnoreWarnings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IgnoreWarnings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
