# coding: utf-8

"""
    X-Road Security Server Admin API

    X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.  # noqa: E501

    OpenAPI spec version: 1.0.31
    Contact: info@niis.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ServiceDescriptionUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'rest_service_code': 'str',
        'new_rest_service_code': 'str',
        'ignore_warnings': 'bool',
        'type': 'ServiceType'
    }

    attribute_map = {
        'url': 'url',
        'rest_service_code': 'rest_service_code',
        'new_rest_service_code': 'new_rest_service_code',
        'ignore_warnings': 'ignore_warnings',
        'type': 'type'
    }

    def __init__(self, url=None, rest_service_code=None, new_rest_service_code=None, ignore_warnings=False, type=None):  # noqa: E501
        """ServiceDescriptionUpdate - a model defined in Swagger"""  # noqa: E501
        self._url = None
        self._rest_service_code = None
        self._new_rest_service_code = None
        self._ignore_warnings = None
        self._type = None
        self.discriminator = None
        self.url = url
        if rest_service_code is not None:
            self.rest_service_code = rest_service_code
        if new_rest_service_code is not None:
            self.new_rest_service_code = new_rest_service_code
        if ignore_warnings is not None:
            self.ignore_warnings = ignore_warnings
        self.type = type

    @property
    def url(self):
        """Gets the url of this ServiceDescriptionUpdate.  # noqa: E501

        path for the service description file  # noqa: E501

        :return: The url of this ServiceDescriptionUpdate.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ServiceDescriptionUpdate.

        path for the service description file  # noqa: E501

        :param url: The url of this ServiceDescriptionUpdate.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def rest_service_code(self):
        """Gets the rest_service_code of this ServiceDescriptionUpdate.  # noqa: E501

        service code for REST service  # noqa: E501

        :return: The rest_service_code of this ServiceDescriptionUpdate.  # noqa: E501
        :rtype: str
        """
        return self._rest_service_code

    @rest_service_code.setter
    def rest_service_code(self, rest_service_code):
        """Sets the rest_service_code of this ServiceDescriptionUpdate.

        service code for REST service  # noqa: E501

        :param rest_service_code: The rest_service_code of this ServiceDescriptionUpdate.  # noqa: E501
        :type: str
        """

        self._rest_service_code = rest_service_code

    @property
    def new_rest_service_code(self):
        """Gets the new_rest_service_code of this ServiceDescriptionUpdate.  # noqa: E501

        new service code for REST service  # noqa: E501

        :return: The new_rest_service_code of this ServiceDescriptionUpdate.  # noqa: E501
        :rtype: str
        """
        return self._new_rest_service_code

    @new_rest_service_code.setter
    def new_rest_service_code(self, new_rest_service_code):
        """Sets the new_rest_service_code of this ServiceDescriptionUpdate.

        new service code for REST service  # noqa: E501

        :param new_rest_service_code: The new_rest_service_code of this ServiceDescriptionUpdate.  # noqa: E501
        :type: str
        """

        self._new_rest_service_code = new_rest_service_code

    @property
    def ignore_warnings(self):
        """Gets the ignore_warnings of this ServiceDescriptionUpdate.  # noqa: E501

        if true, any ignorable warnings are ignored. if false (or missing), any warnings cause request to fail  # noqa: E501

        :return: The ignore_warnings of this ServiceDescriptionUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._ignore_warnings

    @ignore_warnings.setter
    def ignore_warnings(self, ignore_warnings):
        """Sets the ignore_warnings of this ServiceDescriptionUpdate.

        if true, any ignorable warnings are ignored. if false (or missing), any warnings cause request to fail  # noqa: E501

        :param ignore_warnings: The ignore_warnings of this ServiceDescriptionUpdate.  # noqa: E501
        :type: bool
        """

        self._ignore_warnings = ignore_warnings

    @property
    def type(self):
        """Gets the type of this ServiceDescriptionUpdate.  # noqa: E501


        :return: The type of this ServiceDescriptionUpdate.  # noqa: E501
        :rtype: ServiceType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ServiceDescriptionUpdate.


        :param type: The type of this ServiceDescriptionUpdate.  # noqa: E501
        :type: ServiceType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServiceDescriptionUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceDescriptionUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
